
export const photoData =  [
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_2909.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3788.JPG',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3789.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3790.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3791.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3794.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3792.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3793.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3785.JPG',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3796.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3795.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3797.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3801.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3798.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3800.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3799.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3787.JPG',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3802.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3803.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/gem-tree-mums-cover-art-web%400.5x.JPG',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/IMG_3804.jpg',
    'https://gemtreemedia.s3.us-east-2.amazonaws.com/gemphotos/gemwithgrills.jpg',

]